from __future__ import annotations

from typing import Literal, TypedDict

FindingKind = Literal["actual", "noise", "ambiguous"]


class CweExample(TypedDict):
    cwe: str
    title: str
    language: str
    kind: FindingKind
    path: str
    notes: str


CWE_EXAMPLES: list[CweExample] = [
    {
        "cwe": "CWE-79",
        "title": "DOM/reflected HTML injection",
        "language": "python+typescript",
        "kind": "actual",
        "path": "/echo, /cwe/py/html, CweLab.tsx",
        "notes": "User text reaches HTML sinks; paired with escaped variants.",
    },
    {
        "cwe": "CWE-89",
        "title": "SQL query string assembly",
        "language": "python",
        "kind": "actual",
        "path": "/cwe/py/sql and /api/books",
        "notes": "Request field is transformed in propagation code before raw SQL execution.",
    },
    {
        "cwe": "CWE-78",
        "title": "Shell command construction",
        "language": "python+typescript",
        "kind": "actual",
        "path": "/cwe/py/command, cweSinks.ts",
        "notes": "Shell-like strings and subprocess shell execution are explicit research probes.",
    },
    {
        "cwe": "CWE-22",
        "title": "Path traversal / local file read",
        "language": "python+typescript",
        "kind": "actual",
        "path": "/cwe/py/file, cweTransforms.ts",
        "notes": "Weak path normalization is intentionally contrasted with basename-only handling.",
    },
    {
        "cwe": "CWE-94",
        "title": "Code generation / eval",
        "language": "python+typescript",
        "kind": "actual",
        "path": "/cwe/py/eval, supplyProbe.ts, cweSinks.ts",
        "notes": "Dynamic code is reachable only from explicit lab controls.",
    },
    {
        "cwe": "CWE-502",
        "title": "Unsafe deserialization",
        "language": "python+typescript",
        "kind": "actual",
        "path": "/cwe/py/deser, orderRiskChain.ts",
        "notes": "Pickle/YAML and XML object parsing examples exercise deserializer rules.",
    },
    {
        "cwe": "CWE-918",
        "title": "Server/client-side request forgery style fetch",
        "language": "python+typescript",
        "kind": "actual",
        "path": "/cwe/py/ssrf, catalogSidecar.ts",
        "notes": "URL pieces are accepted from request/UI and passed to HTTP clients.",
    },
    {
        "cwe": "CWE-601",
        "title": "Open redirect",
        "language": "python+typescript",
        "kind": "actual",
        "path": "/cwe/py/redirect, cweSinks.ts",
        "notes": "Untrusted URL forwarding is paired with same-origin-only variants.",
    },
    {
        "cwe": "CWE-1333",
        "title": "Inefficient regular expression complexity",
        "language": "python+typescript",
        "kind": "actual",
        "path": "/lab/redos, /cwe/py/regex, cweSinks.ts",
        "notes": "Patterns are capped in route code so the app stays responsive.",
    },
    {
        "cwe": "CWE-352",
        "title": "CSRF-shaped state change",
        "language": "python+typescript",
        "kind": "ambiguous",
        "path": "/cwe/py/csrf-note, CweLab.tsx",
        "notes": "Cookie auth and permissive CORS create a signal, but browser and SameSite behavior may mitigate cases.",
    },
    {
        "cwe": "CWE-200",
        "title": "Information exposure",
        "language": "python+typescript",
        "kind": "actual",
        "path": "/api/exposed/users, /cwe/py/diagnostics",
        "notes": "Diagnostics intentionally echo environment and auth-adjacent metadata.",
    },
    {
        "cwe": "CWE-532",
        "title": "Sensitive data in logs",
        "language": "python",
        "kind": "actual",
        "path": "/v1/ops/login_diagnostics, /cwe/py/diagnostics",
        "notes": "Password-like fields are logged for legacy helpdesk replay.",
    },
    {
        "cwe": "CWE-798",
        "title": "Hardcoded credentials",
        "language": "python+typescript",
        "kind": "noise",
        "path": "bookstore/sast_tiered, cweSinks.ts",
        "notes": "Static sample credentials are clearly non-production and not accepted by auth.",
    },
    {
        "cwe": "CWE-327",
        "title": "Broken or risky crypto algorithm",
        "language": "python+typescript",
        "kind": "noise",
        "path": "findings_diversity.py, cweSinks.ts",
        "notes": "MD5/SHA1 checksums are used for labels, not security decisions.",
    },
    {
        "cwe": "CWE-330",
        "title": "Insecure randomness",
        "language": "python+typescript",
        "kind": "noise",
        "path": "low_severity_bag.py, cweSinks.ts",
        "notes": "Random IDs are display-only tokens in the lab panel.",
    },
    {
        "cwe": "CWE-295",
        "title": "Certificate validation disabled",
        "language": "python",
        "kind": "noise",
        "path": "medium_severity_bag.py",
        "notes": "Unverified TLS contexts sit behind dead branches for scanner calibration.",
    },
    {
        "cwe": "CWE-611",
        "title": "XXE / XML external entity",
        "language": "python+typescript",
        "kind": "noise",
        "path": "/cwe/py/noise/xml-safe, cweTransforms.ts",
        "notes": "Safe XML path uses defused parsing or string-only handling.",
    },
    {
        "cwe": "CWE-20",
        "title": "Improper input validation",
        "language": "python+typescript",
        "kind": "ambiguous",
        "path": "/cwe/py/diagnostics, orderRiskChain.ts",
        "notes": "Weak validation feeds diagnostics rather than privileged decisions.",
    },
    {
        "cwe": "CWE-400",
        "title": "Resource exhaustion",
        "language": "python+typescript",
        "kind": "ambiguous",
        "path": "/cwe/py/regex, cweSinks.ts",
        "notes": "Inputs are bounded to preserve app health but still look like expensive work.",
    },
    {
        "cwe": "CWE-209",
        "title": "Verbose error details",
        "language": "python+typescript",
        "kind": "noise",
        "path": "/cwe/py/diagnostics, App.tsx",
        "notes": "Errors are echoed in a lab-only panel.",
    },
    {
        "cwe": "CWE-284",
        "title": "Access control gaps",
        "language": "python",
        "kind": "actual",
        "path": "/api/orders/*, /cwe/py/diagnostics",
        "notes": "Authorization checks are intentionally loose in research routes.",
    },
    {
        "cwe": "CWE-863",
        "title": "Incorrect authorization",
        "language": "python",
        "kind": "actual",
        "path": "/api/orders/*",
        "notes": "Order policy logic contains permissive legacy roles.",
    },
    {
        "cwe": "CWE-276",
        "title": "Incorrect default permissions",
        "language": "python",
        "kind": "noise",
        "path": "Dockerfile, findings_diversity.py",
        "notes": "World-writable style examples are bounded to temp/demo paths.",
    },
    {
        "cwe": "CWE-732",
        "title": "Incorrect permission assignment",
        "language": "python",
        "kind": "noise",
        "path": "Dockerfile, findings_diversity.py",
        "notes": "Container and code examples are present for policy scanners.",
    },
    {
        "cwe": "CWE-319",
        "title": "Cleartext transmission",
        "language": "python+typescript",
        "kind": "noise",
        "path": "/cwe/py/ssrf, cweSinks.ts",
        "notes": "HTTP URLs are used in local demos, often loopback-only.",
    },
    {
        "cwe": "CWE-345",
        "title": "Insufficient authenticity verification",
        "language": "typescript",
        "kind": "noise",
        "path": "cweTransforms.ts",
        "notes": "Unsigned token parsing is local-only and not trusted by the backend.",
    },
    {
        "cwe": "CWE-347",
        "title": "Improper signature verification",
        "language": "typescript",
        "kind": "noise",
        "path": "cweSinks.ts",
        "notes": "JWT-like parsing is displayed but not accepted for auth.",
    },
    {
        "cwe": "CWE-434",
        "title": "Unrestricted upload-like handling",
        "language": "python+typescript",
        "kind": "noise",
        "path": "/cwe/py/file, CweLab.tsx",
        "notes": "File-name handling is string-only unless explicit local read endpoint is called.",
    },
    {
        "cwe": "CWE-915",
        "title": "Prototype pollution / object injection",
        "language": "typescript",
        "kind": "actual",
        "path": "cweTransforms.ts, cweSinks.ts",
        "notes": "Merged object keys model client-side pollution rules.",
    },
    {
        "cwe": "CWE-1021",
        "title": "Missing anti-clickjacking header",
        "language": "python",
        "kind": "noise",
        "path": "app.py / response headers",
        "notes": "Header absence is intentional for container/app policy testing.",
    },
]
