apiVersion: v1
kind: Service
metadata:
  name: vulnerable-bookstore
  namespace: vulnerable-bookstore-research
  labels:
    app: vulnerable-bookstore
spec:
  selector:
    app: vulnerable-bookstore
  ports:
    - name: http
      port: 3333
      targetPort: 3333
  type: ClusterIP
